import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { useSelector } from "react-redux";
// import { useEffect, useState } from 'react';
// import axios from 'axios';
import Layout from '../components/Layout';
import GlitchText from '../components/GlitchText';
import MultiColorText from '../components/MultiColorText';
import FloatingButton from '../components/FloatingButton';
import { apiDomain, domain, ResumeLink } from '../config/mediaUrls';
import BlogCard from '../components/BlogCard';

const Home: NextPage = ({ posts }: any) => {
  const user = useSelector((state: any) => state.user);

  return (
    <div className='open'>
      <Head>
        <title>Adarsh M : Full Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout classnames='flex flex-col bg-[#f5fff8]'>
        <div className="container mx-auto" style={{ height: "74vh", display: "flex", justifyContent: "center", alignItems: "flex-end", paddingBottom: "64px" }}>
          {/* background: #f5fff8 url("/logo-icon.svg") no-repeat center center; */}
          <GlitchText title="Full Stack Developer" />
        </div>
        {/* classnames='flex flex-col bg-[#f5fff8]' */}

        <div className="container bg-[#f5fff8] mx-auto">
          <div className={styles.gridSection}>
            <div></div>
            <div>
              <MultiColorText textOne={"Hi, I am"} textTwo={"Adarsh M."} colorOne={"#020202"} colorTwo={"#3048a5"} fontSize={"30px"} />
              <p style={{ color: "#898989", fontSize: "14px" }}>I am a UI/Web Developer and a blogger. I like to code and the tech I love are JavaScript, ReactJS, NodeJS, ExpressJS, MongoDB, GraphQL, and more. I am a self-taught developer and I am always learning new things. It&apos;s more like there are many things to learn.</p>
            </div>
          </div>
        </div>

        <div className='mx-auto max-w-2xl lg:max-w-5xl'>
          <div className='mx-auto grid max-w-xl grid-cols-1 gap-y-20 lg:max-w-none lg:grid-cols-2'>
            <div className="flex flex-col gap-16">
              {posts?.map((item: any) => (
                <BlogCard key={item.id} title={item.title} date={item.updatedDate} excerpt={item.description} url={`${domain}/blog/${item.slug}`} />
              ))}
            </div>
          </div>
        </div>
        <FloatingButton link={ResumeLink} text={"Download Resume"} bottom={"10px"} left={"10px"} className="text-white" />
      </Layout>
    </div>
  )
}


export async function getServerSideProps(context: any) {
  const data = await fetch(`${apiDomain}/posts/allposts`)
  const posts = await data.json();
  return {

    props: {
      posts
    },
  }
}

export default Home