import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useSelector } from "react-redux";
import Navbar from '../components/Navbar';
import { useEffect, useState } from 'react';
import axios from 'axios';
import Layout from '../components/Layout';

const Home: NextPage = () => {
  const user = useSelector((state: any) => state.user);
  const [posts, setPosts] = useState<[]>([]);

  useEffect(() => {
    const listAllPosts = async () => {
      await axios.get('http://localhost:4000/posts/allposts')
        .then((res: any) => {
          setPosts(res.data)
        })
        .catch((err: Error) => console.log(err));
    }

    listAllPosts()
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        {/* <div className="container">
          <div className="col-6">
            {posts?.map((item: any) => {
              return (
                <div key={item._id}>
                  <h2>{item.title}</h2>
                  <div dangerouslySetInnerHTML={{ __html: item.description }}></div>
                </div>
              )
            })}
          </div>
        </div> */}
      </Layout>
    </div>
  )
}

export default Home
