/* eslint-disable @next/next/no-img-element */
import axios from "axios"
import Head from "next/head"
import Link from "next/link"
import React, { useEffect, useState } from "react"
import Layout from "../../components/Layout"
import { apiDomain } from "../../config/mediaUrls"

type Post = {
    id: any,
    title: string,
    description: string,
    author: string,
    status: string,
    updatedDate: Date,
    slug: string,
    featuredImg: string
}

export default function Blog() {
    const [posts, setPosts] = useState([])
    const [filterPosts, setFilterPosts] = useState([])

    useEffect(() => {
        const getPostByUser = async () => {
            var config = {
                method: 'get',
                url: `${apiDomain}/posts/allposts`,
            };
            const posts = await axios(config)
            const publishedPosts = posts.data.filter((post: any) => post.status === 'PUBLISH')
            setPosts(publishedPosts)
            setFilterPosts(publishedPosts)
        }
        getPostByUser();
    }, [])

    function searchPost(keyword: string) {
        if (keyword.length > 3) {
            setFilterPosts(posts.filter((post: Post) => post?.title?.toLowerCase().includes(keyword) || post?.slug?.toLowerCase().includes(keyword)))
        }
        if (keyword.length === 0) {
            setFilterPosts(posts)
        }
    }

    return (
        <React.Fragment>
            <Head>
                <title>Blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <div className="header-blog">
                    <h2 className="text-3xl">My Blog</h2>
                    <div className="flex flex-col justify-center items-center gap-2 text-center">
                        <input type="text" placeholder="Search for blog title here..." className="p-3 border-0 rounded search-blog-posts mt-4" style={{ width: `clamp(240px, 300px, 600px)` }} onChange={(e) => searchPost(e.target.value)} />
                    </div>
                </div>
                <div className="container mx-auto">
                    {/* <div className="row"> */}
                    <div className="blog-posts-container mt-5">
                        {filterPosts?.map((post: Post) => {
                            return (
                                <div className="p-4" style={{ boxShadow: "6px 0px 16px #f4f4f4" }} key={post.id}>
                                    <div className="flex flex-col gap-3">
                                        <img src={post.featuredImg} className="card-img-top" alt={post.title} style={{ width: "auto", height: `clamp(200px, 240px, 400px)` }} />
                                        <div className="relative">
                                            <h5 className="card-title">{post.title}</h5>
                                            <div className="flex">
                                                <p className="post-updated">{new Date(post.updatedDate).toLocaleDateString('en-IN')}</p> &nbsp;
                                                <p className="">by</p> &nbsp;
                                                <p className="post-author">{post.author}</p>
                                            </div>
                                            <p className="post-excerpt h-16">{post.description}</p>
                                            <Link href={`/blog/${post.slug}`}>
                                                <a className="btn-read-more underline underline-offset-4">
                                                    Read More
                                                </a>
                                            </Link>
                                        </div>
                                    </div>
                                </div>
                            )
                        })}
                    </div>
                    {/* </div> */}
                </div>
            </Layout>
        </React.Fragment>
    )
}